[tasks.cleanmodels]
command = "rm"
args = ["-f", ".models.json"]
workspace = false


[tasks.genmodels]
command = "cargo"
args = ["run", "-r", "-p", "rustymon-server", "-F rorm-main"]
dependencies = ["cleanmodels"]
workspace = false

[tasks.make-migrations]
command = "rorm-cli"
args = ["make-migrations"]
dependencies = ["genmodels"]
workspace = false

[tasks.migrate]
command = "rorm-cli"
args = ["migrate"]
workspace = false

[tasks.build]
command = "cargo"
args = ["build", "-r", "-p", "rustymon-server"]
workspace = false

[tasks.populate-db]
command = "cargo"
args = [
    "run", "-r", "-p", "rustymon-server", "--", "parse-osm",
    "--config-path", "config.toml",
    "--file", "osm_data/bayern-latest.osm.pbf",
    "--center-x", "11.5118905",
    "--center-y", "48.5219287",
]
workspace = false
