[Migration]
Hash = '14907402141296602420'
Initial = true
Replaces = []

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'tile'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int64'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'min_x'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'max_x'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'min_y'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'max_y'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'way'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int64'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'points'
Type = 'varbinary'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'features'
Type = 'varbinary'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'area'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int64'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'points'
Type = 'varbinary'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'features'
Type = 'varbinary'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'node'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int64'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'x'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'y'
Type = 'double_number'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations.Fields]]
Name = 'features'
Type = 'varbinary'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'session'

[[Migration.Operations.Fields]]
Name = 'session_key'
Type = 'varchar'

[[Migration.Operations.Fields.Annotations]]
Type = 'max_length'
Value = 4096

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'session_state'
Type = 'varchar'

[[Migration.Operations.Fields.Annotations]]
Type = 'max_length'
Value = 1048576

[[Migration.Operations.Fields]]
Name = 'expired_after'
Type = 'datetime'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'node'

[Migration.Operations.Field]
Name = 'tile'
Type = 'int64'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'tile'
ColumnName = 'id'
OnDelete = 'Restrict'
OnUpdate = 'Cascade'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'way'

[Migration.Operations.Field]
Name = 'tile'
Type = 'int64'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'tile'
ColumnName = 'id'
OnDelete = 'Restrict'
OnUpdate = 'Cascade'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'area'

[Migration.Operations.Field]
Name = 'tile'
Type = 'int64'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'tile'
ColumnName = 'id'
OnDelete = 'Restrict'
OnUpdate = 'Cascade'
